INSERT INTO barangays VALUES (null, 'Balangobong');
INSERT INTO barangays VALUES (null, 'Bued');
INSERT INTO barangays VALUES (null, 'Bugayong');
INSERT INTO barangays VALUES (null, 'Camangaan');
INSERT INTO barangays VALUES (null, 'Canarvacanan');
INSERT INTO barangays VALUES (null, 'Capas');
INSERT INTO barangays VALUES (null, 'Cili');
INSERT INTO barangays VALUES (null, 'Dumayat');
INSERT INTO barangays VALUES (null, 'Linmansangan');
INSERT INTO barangays VALUES (null, 'Mangcasuy');
INSERT INTO barangays VALUES (null, 'Moreno');
INSERT INTO barangays VALUES (null, 'Pasileng Norte');
INSERT INTO barangays VALUES (null, 'Pasileng Sur');
INSERT INTO barangays VALUES (null, 'Poblacion');
INSERT INTO barangays VALUES (null, 'San Felipe Central');
INSERT INTO barangays VALUES (null, 'San Felipe Sur');
INSERT INTO barangays VALUES (null, 'San Pablo');
INSERT INTO barangays VALUES (null, 'Santa Catalina');
INSERT INTO barangays VALUES (null, 'Santa Maria Norte');
INSERT INTO barangays VALUES (null, 'Santiago');
INSERT INTO barangays VALUES (null, 'Santo Niño');
INSERT INTO barangays VALUES (null, 'Sumabnit');
INSERT INTO barangays VALUES (null, 'Tabuyoc');
INSERT INTO barangays VALUES (null, 'Vacante');
